# Generated by Django 4.1.3 on 2022-12-24 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_remove_employee_last_nmae_alter_employee_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='first_name',
            new_name='Employee_name',
        ),
    ]
