# Generated by Django 4.1.3 on 2022-12-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_rename_first_name_employee_employee_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='dep',
            new_name='dept',
        ),
    ]
