# Generated by Django 4.1.3 on 2022-12-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0005_student_remove_employee_dept_remove_employee_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Student_name',
            new_name='student_name',
        ),
        migrations.AlterField(
            model_name='student',
            name='hire_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
