# Generated by Django 4.1.3 on 2022-12-25 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0006_rename_student_name_student_student_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='dept',
            new_name='dep',
        ),
    ]
