# Generated by Django 4.1.3 on 2022-12-25 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0007_rename_dept_student_dep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dep',
        ),
    ]
